### ISSUE TITLE
Update the concurrent offers validator to account for nonoverlapping offers in a time period

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-be#123]
Right now, the concurrentOffersNotExceeded function, which is used to validate offers in the route and model levels, only counts all offers in a time period for a specific owner. Update this function so it accounts for nonoverlapping offers in the new offer's time period.

For example:

```
|-----------|

       (new offer)
    |---------------|

                 |-----------|
```
In this case, there are only 2 concurrent offers at any given time but, right now, the function will count 3 anyways. A possible solution would be to parse the offers returned by the getOffersInTimePeriod function to count the maximum concurrent ones at any time.

**Comment by imnotteixeira** [comment]
In the current model, this problem is hard since you have a high granularity on the offer times (in the order of seconds).

To achieve this goal you would need to verify the overlap for each second, and if the offer extends for the current maximum period (6 months), there are approx. 15552000 secs which is too much to calculate.

An alternative would be to lower the granularity (e.g. the publish dates would have a "day" granularity), but that would still be 180 days in the worst scenario.

The O(n) solution for this problem is as follows (I think):
1. Fetch all offers that could collide with the new one (the ones that intersect only)
2. Order all offers (including the new one) by publishDate descending
3. iterate the time slots (in this case each day) starting with the offer that has the earliest publishDate and count how many offers are active in that day
4. If some slot has more offers than the limit, stop. This way we can make the algorithm faster in most of the cases

This has a time complexity of **n*t**, *n* being the number of intersecting offers, and *t* the time until a limit surpassing is found, with a maximum t = 180 (for day granularity and current limit of 6 months - assuming 30d/month).

With this in mind, I am open to more suggestions on how to tackle this problem, with possibly some heuristics to further optimize it (maybe storing auxiliary values on offers, at the creation time?)

**Comment by BrunoRosendo** [comment]
When I wrote the issue I thought about just checking every offer to see if they actually collide with one another (even though this is O(n2), the number of offers is fairly small). But after thinking a little more I understood that this would only reduce the problem and not completely fix it, since there are still cases where it would not work. I'm just writing this in case anyone wants to implement this in the meanwhile (since I believe it is better than nothing and it's very simple), until we implement a permanent solution like the one you described.

**Comment by imnotteixeira** [comment]
> I thought about just checking every offer to see if they actually collide with one another

That would only increase the computation time without actually solving anything since they can collide at different times, still. That's not worth doing.

However, following up on the above suggestion, I have a proposal that might be easier to do, and does not depend on the number of days (granularity independent), only on the number of intersections.

1. Fetch all offers that could collide with the new one (the ones that intersect only)
2. Create 2 auxiliary arrays (one for publishDates (let's call it `start`) and another for publishEndDates(let's call it `end`), and put the values there, sorted (The values of `start[i]` and `end[i]` might not correspond to the same offer, they are sorted among their respective array values
3. Starting with the smallest value (which should be in `start[0], since end[0] must be greater than that), loop while there's some value in either of the arrays
  - If the value is coming from `start`, increment the counter (and if > than maximum so far, update maximum)
  - If the value is coming from `end`, decrement the counter
  - In either case, update the "current time", so that you pick the smallest time greater than "current" for next iteration
4. In the end, the maximum of counter will be the maximum concurrent offers in a same time period


I think this is feasible, and still O(n). since sorting should be O(n log(n)). Want to give it a try, @BrunoRosendo ?

**Comment by BrunoRosendo** [comment]
That solution sounds very promising! I was trying to come up with a way of solving the problem without iterating in intervals and I think that will work well. 

Yes,  I'm going to give it a try, thank you.
