### ISSUE TITLE
Offer editing with the same dates not throwing error

### ISSUE THREAD

**Issue by Naapperas** [NIAEFEUP/nijobs-be#151]
Currently, if you edit an offer and put in the request body the fields `publishDate` and `publishEndDate` with exactly the same value, no error is thrown (this is due to parsing one of the dates and not the other when checking).

![image](https://user-images.githubusercontent.com/23704084/115938580-1be3e500-a493-11eb-8241-50f0a8f10966.png)

This request body causes an "OK" response, which is not the desired behaviour.

This problem also happens when creating offers, so that needs to be fixed as well.

**Comment by imnotteixeira** [comment]
We've had related problems in the past, which we solved by converting the dates to Date objects after they were validated. However in these cases where publishDate validation depends on publishEndDate being valid and vice-versa, this solution would sometimes fail since validators are not expected to be run always in the same order, and that gave inconsistent results.

That lead us to the solution we have today, which is based on each validator that requires a date, to do the parsing inside it. The current problem arises from the fact that the parsing is not being done the same way for both dates in the validator

https://github.com/NIAEFEUP/nijobs-be/blob/77edc51fe2743533ffb83b668b3895002961e166/src/api/middleware/validators/offer.js#L250

To solve this, I propose having a custom validator that will normalize the dates as is currently being done in the validator (i.e., `(new Date(Date.parse(publishDateCandidate))).toISOString();`. However, since the validators do not run in same order every time, this normalized function will need to normalize **every** date every time (the publishDate and publishEndDate will be normalized in the publishDate validator, as well as the publishEndDate one, possibly doing duplicate work, but ensuring that all validators are dealing with the same values)

Finally, just for the sake of consistency, we might as well normalize `jobStartDate` to avoid confusion and possibly bugs in the future

**Comment by Naapperas** [comment]
Maybe after #154 work can be started for this issue since that PR includes a `enhanceRequests` method which could be used when normalizing dates present in the request body.

**Comment by imnotteixeira** [comment]
> Maybe after #154 work can be started for this issue since that PR includes a `enhanceRequests` method which could be used when normalizing dates present in the request body.

Those are different things, one targets the whole application, and this one is specific to the offer creationg/editing, it should be placed inside this more restricted scope.
