### ISSUE TITLE
Add auditing to CI

### ISSUE THREAD

**Issue by xRuiAlves** [NIAEFEUP/nijobs-be#18]
I think it would be interesting to add package auditing to the continuous integration to avoid (at least to filter `high` vulnerabilities) to keep our packages clean-ish.

**Comment by miguelpduarte** [comment]
I believe you have had some experience regarding this - can you work on it?

We can also take the chance to investigate several CI systems: Have heard good things about circleci, maybe we can change to it?

**Comment by miguelpduarte** [comment]
Dependabot might be also helping with this, should we consider closing this in favour of dependabot? Or would some extra automation be useful to have a "security dashboard" all the same? (cc @imnotteixeira)

**Comment by imnotteixeira** [comment]
I think we should have both:

When requesting a PR that changes dependencies (adding/removing/updating packages), it's important to know if it caused some audit problem for it to be solved there.

For PRs that don't mess with dependencies but still fail the audit check (because with time vulnerabilities are found anyway), we can solve the issue by using dependabot (hopefully it will have opened a PR as the vulnerability is on `develop` as well) and then rebase the change to this PR so as not to mix both problems.
