### ISSUE TITLE
Add README badge for code coverage

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-be#248]
NIJobs has a pretty good test coverage of all its features but we're not showcasing it to everyone. It'd be nice to have a badge showing how much coverage we have.

One could look into [Codecov](https://about.codecov.io/) or a similar tool. We should be able to easily integrate it with our Github actions. CI. You can look at multiple projects using this, but here's an example: https://github.com/codecov/example-javascript.

It's also possible to integrate this tool with pull requests and it'll tell us how the coverage has increased or decreased. We can consider using this if we think is worth it.

**Comment by ttoino** [comment]
I've looked into Codecov a bit more, the organization should have access to it now, but the implementation is gonna be harder than expected due to the fact that we are using docker to run our tests.

I've thought of two ways to deal with this:

- Creating a new npm script that runs the tests and uploads the coverage from within the docker container (not that hard but probably more time consuming and unsafe);
- Creating a shared coverage volume in the container so we can use the [built in Codecov github action](https://github.com/marketplace/actions/codecov) (this has the added benefit of letting us see the coverage after running the test script locally).

**Comment by Naapperas** [comment]
In my opinion, the second option is better but a second opinion would be appreciated. What do you think @BrunoRosendo ?
