### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by nip10** [NIAEFEUP/nijobs-be#31]
Although this project already uses Docker, which basically eliminates issues that arrise from using different environments, there are still some issues that cause errors on Windows.

The **TLDR** is that `npm test` and pushing to git don't work on Windows.

The `test` script doesn't work in Windows due to the way env vars are set, plus the way two consecutive commands are executed in cmd. The best solution that I'm aware of is to use the [cross-env](https://www.npmjs.com/package/cross-env) package. The issue with pushing to git is due to the pre-push hook that calls that same npm script.

(I was previously able to edit the code and run the tests by manually editing the npm script)

**Comment by miguelpduarte** [comment]
I'm not sure that this is a concern to the dev team, as the majority uses Linux (hence this not having been a problem yet), and those that might use Windows are using something like WSL most likely.

The most that I think would make sense here would be simply to remove the git hooks. I don't see much use in them, as the checks should be done in CI anyway (being that the local checks can be bypassed by `--no-verify` and are just a slowdown in development, as we have to wait for the linter/tests to run).
Since CI is already setup (and might be improved soon too, relative to #24), they really become pointless.

Since it is possible to run the tests using the docker configuration anyway, I'd say that this (removing the hooks) would be enough to have a decent enough Windows support. Even so, I'll page someone else on the team to get a second opinion.

**Comment by miguelpduarte** [comment]
Hooks are also less than ideal since they are only installed if one runs `npm install` directly, which means that someone that always uses Docker will never run them.

**Comment by imnotteixeira** [comment]
I also am not keen on this. Extra dependencies mean extra vulnerabilities or maintenance problems. 

Regarding the disablement of hooks, after talking with @miguelpduarte and further thinking about it, I agree that they are not really necessary and should be removed, provided that the checks are done on the PR.

Also regarding the test command not running on windows, that is due to the env var set there. However, that var could be removed if we re-think the way we do testing. I believe that var is set so that the server is started in 'test mode', in order to do some end-to-end testing, but I think we can change them in order to have unit tests with some mocking, which can be tackled as part of #25.

The end-to-end tests can still be done via another command that just runs the e2e tests on a specific folder (a different package would be ideal, but not sure if CircleCI supports running tests in a different package in order to approve this one). With this, the developers could run the unit tests to check faster their code quality, and eventually the e2e tests, just to make sure that everything works, and we could still run both sets of tests in CI validation.

This would solve the problem as the windows users could run the test command without problems.

**Comment by miguelpduarte** [comment]
Setting `NODE_ENV` is important for both production and testing because of the way some packages change their behavior based on its value (such as `dotenv-flow` and `express`, for example).
However, as @imnotteixeira mentioned, switching to Jest will probably remove the need to do that, as it probably is handled internally by this package (thus #25, as well).

> This would solve the problem as the windows users could run the test command without problems.

This is true given the above, and windows users can already run the test suites using Docker, so I really don't see a problem there :+1: 

Will close this and the accompanying PR. Should probably open an issue to track the desire to remove git hooks though. (Simple enough)

**Comment by nip10** [comment]
I've pretty much only used Windows for web-dev ever since I started, but I agree Docker is enough for development.

Regarding hooks, I don't really have a strong opinion on them - I never ran tests via hooks and having eslint+prettier acting onSave on my editor are pretty much enough. That said, I still can see a valid argument on using them for linting since some errors that require manual fixes may go unnoticed.
