### ISSUE TITLE
Improve validation

### ISSUE THREAD

**Issue by nip10** [NIAEFEUP/nijobs-be#33]
In the /register route, both username and password lack proper validation. A string consisting of spaces will be valid and saved in the database.

A possible solution is to use `trim()` and then `length`. A more robust (but more complex) solution is to use something like [@hapi/joi](https://www.npmjs.com/package/@hapi/joi).

Mongoose models can also have `required` and `validate` fields.

**Comment by miguelpduarte** [comment]
I see no problem with allowing spaces in the password. I am not entirely up to date on web development good practices for sure, but I don't see why the password's characters should be restricted at all.

Relative to the username - there I'd say you have a point. We could decide on certain requirements and follow them - such as "only alphanumerical characters" or something like that.

Finally, on using `@hapi/joi` - I'd have to say that I'm against it because despite seeming like a more robust solution, what I really see is just one more package that does not simplify things all that much - we could (and should, imo) make our own validators, which we can reuse to make more complex ones. The logic that it abstracts does not seem to be enough justification to make it worthwhile.

As you can see, I'm very purist in what concerns utility packages :sweat_smile:
I really hate bloat and will many times prefer to implement stuff myself instead of relying on other stuff.

I know, I know, "don't reinvent the wheel!" - However, my wheel is not dependant on other people making it not spin anymore without apparent reason, or providing no help when the wheel stops working for no reason! (which sadly is many times the case for `node` packages)

However, of course, this is not set in stone - if it makes sense to add later, then of course that would be best! It just doesn't seem to me like a necessary course of action for now, so I'd rather go with the simplest approach.

**Comment by nip10** [comment]
The issue is not having spaces, but being entirely spaces. The `trim `function will only remove leading and trailing spaces, not spaces in the middle. (but since you mentioned it, I'm pro disallowing any spaces at all)

Using Joi was only a suggestion. I find it pretty useful (eg email validation, error handling) but I can see it being a bit overhead for the current schemas.
