### ISSUE TITLE
Fix validation (contacts)

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#51]
When using the API naively, I did not know the contacts format so just assumed an array of strings. It did not give me a validation error, as it should.

After this, I started thinking about what should be the format. First, a single string could be enough, but that's not very informative, and the company might have more than a point of contact.
So I think it's best to have a Map(String, String) to match a name/person to an email/phone number so that it is more informative on who the candidate will be talking to. Maybe there will be cases where the email is generic and no specific person will be linked.. Simple: use map(email, person) where the second can be an empty string

**Comment by miguelpduarte** [comment]
It seems that validating a key-value pair is not possible as of yet by using [`validator.js`](https://github.com/validatorjs/validator.js#validators) (what `express-validator` uses for the validation itself).

There is a `isJSON` validator that uses `JSON.parse` but that seems like it would be too loose a constraint (what would happen if the input was `{general_email: [hey, hey, you, you]}`? I have no idea...)

So, it is highly likely that we would have to extend that validator, or use it with some custom validation on top of it as well. As such, mind if I put this on the backburner for a bit? Need to investigate some more and would rather tackle some other more pressing concerns.

**Comment by miguelpduarte** [comment]
Furthermore, I don't agree with the map(email, person) when the person can be empty. I would see it as every contact having a key as description. Otherwise, a contacts array would suffice.

In that case it could just be `{general_email: info@company.com}`

**Comment by miguelpduarte** [comment]
And this makes me wonder, and want to pull discussion in this direction: Why, in fact, not just use an array? If these are job postings for companies, the contacts will likely be either recruiter emails (like jdoe@company.com) and phone numbers or general recruiting company division emails (like jobs@company.com).

As such, do these fields really need annotation in the form of key-value pairs? It seems like requiring one to be given and allowing multiple to exist would be enough, since they would be self-descriptive.

(There is also the bonus point of the `.isArray` validator already being implemented :stuck_out_tongue:)

**Comment by imnotteixeira** [comment]
Even though I still think the map is a better option, that can only be validated with our company-users once we launch. For now, I agree that an array may suffice.
